version: '3.4'

services:
  testspadocker:
    image: ${DOCKER_REGISTRY-}testspadocker
    build:
      context: .
      dockerfile: TestSPADocker\Dockerfile

  clientapp:
    image: ${DOCKER_REGISTRY-}clientapp
    build:
      context: .
      dockerfile: Web.Client\Dockerfile

